nome = str(input('Digite seu nome completo: ')).strip()
print(f'Seu nome maiúsculo: {nome.upper()}')
print(f'Seu nome minúsculo: {nome.lower()}')
numero = len(nome)-nome.count(' ')
print(f'Seu nome tem {numero} letras.')
primeiro = nome.find(' ')
print(f'Seu primeiro nome tem {primeiro} letras.')
lista = nome.split()
nome1 = len(lista[0])
print(f'O seu primeiro nome é {lista[0]} e ele tem {nome1} letras.')
